### ISSUE TITLE
Installation fails: blockchain_state & dht_state files not created

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-search#28]
I did the following:

1) Cloned the repo
2) Created a virtualenv
3) Installed requirements `pip install -r requirements.txt`
4) Changed search/config.py to point to my local resolver
5) Ran `python -m search.basic_index --refresh` and got the following error
```
(venv)root@blockstack:/srv/blockstack-search# python -m search.basic_index --refresh
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/srv/blockstack-search/search/basic_index.py", line 275, in <module>
    flush_db()
  File "/srv/blockstack-search/search/basic_index.py", line 138, in flush_db
    client.drop_database('search_db')
  File "/srv/blockstack-search/venv/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 929, in drop_database
    read_preference=ReadPreference.PRIMARY)
  File "/srv/blockstack-search/venv/local/lib/python2.7/site-packages/pymongo/database.py", line 451, in command
    with client._socket_for_reads(read_preference) as (sock_info, slave_ok):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/srv/blockstack-search/venv/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 699, in _socket_for_reads
    with self._get_socket(read_preference) as sock_info:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/srv/blockstack-search/venv/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 663, in _get_socket
    server = self._get_topology().select_server(selector)
  File "/srv/blockstack-search/venv/local/lib/python2.7/site-packages/pymongo/topology.py", line 121, in select_server
    address))
  File "/srv/blockstack-search/venv/local/lib/python2.7/site-packages/pymongo/topology.py", line 97, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
(venv)root@blockstack:/srv/blockstack-search#
```
6) Installed mongodb `apt-get install mongodb`
7) Ran `python -m search.basic_index --refresh` again and got following error:
```
(venv)root@blockstack:/srv/blockstack-search# python -m search.basic_index --refresh
[11 Apr 2016 10:12:47] [DEBUG]	[__main__]:	Flushed DB
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/srv/blockstack-search/search/basic_index.py", line 276, in <module>
    fetch_dht_state_from_file()
  File "/srv/blockstack-search/search/basic_index.py", line 63, in fetch_dht_state_from_file
    dht_file = open(DHT_STATE_FILE, 'r')
IOError: [Errno 2] No such file or directory: '/srv/blockstack-search/search/data/dht_state.json'
(venv)root@blockstack:/srv/blockstack-search#
```
8) I created `search/data` and touched `search/data/dht_state.json`.
9) Ran `python -m search.basic_index --refresh` again and got following error:
```
(venv)root@blockstack:/srv/blockstack-search# python -m search.basic_index --refresh
[11 Apr 2016 10:19:53] [DEBUG]	[__main__]:	Flushed DB
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/srv/blockstack-search/search/basic_index.py", line 276, in <module>
    fetch_dht_state_from_file()
  File "/srv/blockstack-search/search/basic_index.py", line 66, in fetch_dht_state_from_file
    dht_state = json.loads(dht_state)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
(venv)root@blockstack:/srv/blockstack-search#
```
10) I added an empty JSON objoct `{}` to `search/data/dht_state.json` and ran `python -m search.basic_index --refresh` with the same errors but for `search/data/blockchain_state.json`
11) Repeated steps 8-10 for `search/data/blockchain_state.json`
12) Ran `python -m search.basic_index --refresh` again with the following output:
```
(venv)root@blockstack:/srv/blockstack-search# python -m search.basic_index --refresh
[11 Apr 2016 10:21:49] [DEBUG]	[__main__]:	Flushed DB
[11 Apr 2016 10:21:49] [DEBUG]	[__main__]:	-----
[11 Apr 2016 10:21:49] [DEBUG]	[__main__]:	Fetching DHT state from file
[11 Apr 2016 10:21:49] [DEBUG]	[__main__]:	-----
[11 Apr 2016 10:21:49] [DEBUG]	[__main__]:	Fetching namespace from file
[11 Apr 2016 10:21:49] [DEBUG]	[__main__]:	-----
[11 Apr 2016 10:21:49] [DEBUG]	[__main__]:	Creating search index
[11 Apr 2016 10:21:49] [DEBUG]	[__main__]:	Optimized DB
[11 Apr 2016 10:21:49] [DEBUG]	[__main__]:	Created name/twitter/username search index
(venv)root@blockstack:/srv/blockstack-search#
```
13) Continuing on to the Quick Testing section, i ran `python -m search.substring_search --search_twitter fredwil` with the following output:
```
[]
-----
[]
(venv)root@blockstack:/srv/blockstack-search#
```
No results. Upon further investigation, it appears that `python -m search.basic_index --refresh` didn't populate `dht_state.json` and `blockchain_state.json`. Am I doing something wrong?

**Comment by muneeb-ali** [comment]
@larrysalibra thanks for reporting this. I have some unmerged changes that I need to push to this repo which automate the creation of dht_state.json and blockchain_state.json. 

You can download these temporary files just for testing:
1) [dht_state.json](http://muneebali.com/static/files/dht_state.json)
2) [blockchain_state.json](http://muneebali.com/static/files/blockchain_state.json)

The blockchain_state is basically a subset of the data in your blockstack-server DB. And dht_state is data from a DHT mirror (should be widely replicated across mirrors). 

Our plan is to actually start combining search and resolver with blockstack-server and have a HTTP interface and documentation for it (like you see on api.onename.com). I'll start separate Github issues for that goal. Once completed, running resolver and search should become much simpler. Of course, we need to do a bunch of work around making deployment easier as well with scripts to automate things.

I'll follow up on this issue when I push my scripts for constructing the two state files.
